# config/config.yaml

# Plex Configuration
plex:
  token: "${PLEX_TOKEN}"  # Your Plex token from .env
  host: "${PLEX_HOST}"    # Your Plex host URL from .env

# Time Zone Configuration
timezone: "America/Chicago"  # Time zone for scheduling and date calculations

# Directories Configuration
directories:
  base_pre_roll_dir: "/pre-rolls/plex"  # Base directory for pre-roll videos

# Schedule Configuration
schedule:
  tasks:
    - name: "Daily Pre-Roll Update"
      time: "14:30"  # Time to run the update (HH:MM in 24-hour format)

# Holidays Configuration
holidays:
  - name: "New Years"
    start_date: "12-26"  # MM-DD format
    end_date: "01-04"    # MM-DD format
    pre_rolls:
      - "christmas/Snow Globe Plex Pre-roll.mp4"
      - "christmas/Another Pre-roll.mp4"
    selection_mode: "random"  # Options: "random", "sequential"

  - name: "Valentine's Day"
    start_date: "02-01"
    end_date: "02-28"
    pre_rolls:
      - "valentine/Valentine Pre-roll.mp4"
    selection_mode: "random"

  - name: "Easter"
    start_date: "03-20"
    end_date: "04-30"
    pre_rolls:
      - "easter/Easter Pre-roll.mp4"
    selection_mode: "random"

  - name: "Mother"
    start_date: "05-05"
    end_date: "05-10"
    pre_rolls:
      - "mother/Mother's Day Pre-roll.mp4"
    selection_mode: "random"

  - name: "Memorial"
    start_date: "05-18"
    end_date: "06-07"
    pre_rolls:
      - "memorial/Memorial Day Pre-roll.mp4"
    selection_mode: "random"

  - name: "Independence"
    start_date: "06-23"
    end_date: "07-11"
    pre_rolls:
      - "independence/Independence Day Pre-roll.mp4"
    selection_mode: "random"

  - name: "Labor"
    start_date: "09-01"
    end_date: "09-10"
    pre_rolls:
      - "labor/Labor Day Pre-roll.mp4"
    selection_mode: "random"

  - name: "Halloween"
    start_date: "10-01"
    end_date: "10-31"
    pre_rolls:
      - "halloween/Halloween Pre-roll.mp4"
      - "halloween/Halloween Pre-roll2.mp4"
    selection_mode: "sequential"

  - name: "Thanksgiving"
    start_date: "11-01"
    end_date: "11-30"
    pre_rolls:
      - "thanksgiving/Thanksgiving Pre-roll.mp4"
    selection_mode: "random"

  - name: "Christmas"
    start_date: "12-01"
    end_date: "12-25"
    pre_rolls:
      - "christmas/Christmas Pre-roll.mp4"
    selection_mode: "random"
